# Generated by Django 5.0 on 2023-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('year', models.IntegerField()),
                ('discription', models.TextField()),
                ('movie_image', models.ImageField(upload_to='movie_images')),
            ],
        ),
    ]
